### ISSUE TITLE
Code problem

### ISSUE THREAD

**Issue by Alexwanp** [kilsenp/triplet-reid-pytorch#3]
Hello, thank you for the code provided, which has greatly helped my research work, but there is a problem with running your code. I didn't understand the problem. I hope to get your help, thank you

Traceback (most recent call last):
  File "train.py", line 304, in <module>
    log.save_args(args)
  File "C:\Users\ST\Desktop\triplet-reid-pytorch-master\logger.py", line 89, in save_args
    label = subprocess.check_output(["git", "describe", "--always"]).strip().decode()
  File "C:\Program Files\Python35\lib\subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "C:\Program Files\Python35\lib\subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python35\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python35\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by kilianyp** [comment]
Hi,
I'm glad that my code has been useful to you.
I haven't tested the code on windows, but I'm guessing that you either haven't installed git or are not using the git console. 
That part is just for logging the current git commit, nothing essential. For a quick and dirty workaround you could just comment that line out. 
But its better if you installed git and setup your PATH variable properly, then it should also work on windows.

Best,
Kilian
